### PR TITLE
Topic/include agent version in http request

### PR DESCRIPTION
**Pull request by leonardojoao**

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
The agent version is always a semantic version right? If so, it'd be good to validate that.

@gustavosbarreto should we add those checks now?

**Comment by gustavosbarreto** [comment]
> The agent version is always a semantic version right? If so, it'd be good to validate that.

No, not always. In development mode the version is hard-coded to "latest".

> @gustavosbarreto should we add those checks now?

Nice find, but this should be fixed in a separate commit.

**Comment by gustavosbarreto** [comment]
@leonardojoao please append what issue this PR closes to the last commit message.

**Comment by leonardojoao** [comment]
@gustavosbarreto 
Do I quote the same issue on both commits?

**Comment by otavio** [comment]
> > The agent version is always a semantic version right? If so, it'd be good to validate that.
> 
> No, not always. In development mode the version is hard-coded to "latest".

Sure, in this case we can check if it is "latest" or a semver.

**Comment by gustavosbarreto** [comment]
> @gustavosbarreto
> Do I quote the same issue on both commits?

No, just on the commit that changes the agent code.

**Pull request merged**
