### PR TITLE
fix(gateway): pass request headers to install script route

### PR DESCRIPTION
**Pull request by henrybarreto**

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
Could you kindly enhance the commit log by providing a clear explanation of the issue it resolves and the reason behind it?

**Comment by otavio** [comment]
Also, add `Fixes: #2858`

**Comment by henrybarreto** [comment]
> Could you kindly enhance the commit log by providing a clear explanation of the issue it resolves and the reason behind it?

Of course. I'll do.

**Review by otavio — APPROVED** [review]
LGTM.

**Pull request merged**
