### PR TITLE
cli: ensure the username and email stored in lowercase

### PR DESCRIPTION
**Pull request by Asakiz**
Signed-off-by: asakiz <asakizin@gmail.com>

### CODE REVIEW

**Review by otavio — APPROVED** [review]

**Comment by otavio** [comment]
The fix is fine, do we need to add a migration to handle existing data?

**Comment by otavio** [comment]
I just found #977. This two are related.

**Comment by Asakiz** [comment]
> I just found #977. This two are related.

I think @eduardoveiga cherry pick the commit and merge on his PR.

**Comment by Asakiz** [comment]
> The fix is fine, do we need to add a migration to handle existing data?

And yes, we need a migration to make sure all the data is in the same pattern.

**Comment by otavio** [comment]
@Asakiz agreed. @eduardoveiga can you do this and close this PR?

**Comment by eduardoveiga** [comment]
> @Asakiz agreed. @eduardoveiga can you do this and close this PR?

yes, i will do this now

**Pull request closed without merging**
