### PR TITLE
api: add worker to delete session records

### PR DESCRIPTION
**Pull request by henrybarreto**

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
Where do we define the time window to preserve? For example, to remove sessions older than 90 days.

**Comment by henrybarreto** [comment]
That first implementation was intended to be an env variable, but the next one will empower each namespace to set it own time interval at the settings panel.

**Comment by otavio** [comment]
Sure, it makes sense. But it is not defined in this PR. Is it?

**Comment by henrybarreto** [comment]
> Sure, it makes sense. But it is not defined in this PR. Is it?

Yes, that was I've intended, but it is not well documented at PR.

**Pull request merged**
