### PR TITLE
fix docker compose binary

### LINKED ISSUE #3464: Incompatible docker compose version
### Description

I just installed the community edition of shellhub and when adding a user using `./bin/add-user` I got an error

```
./bin/add-user: line 9: docker-compose: command not found
```

This was easily fixed by modifying the script to remove the `-` since the command for docker-compose is now `docker compose`. This needs to be updated in all the scripts

### Edition

Community

### Version

0.13.1

### PR DESCRIPTION
**Pull request by heiytor**
fixes #3464

### CODE REVIEW

**Review by Seluj78 — APPROVED** [review]
LGTM !

**Review by gustavosbarreto — CHANGES_REQUESTED** [review]
1) `$COMPOSE_ARGS` is no longer defined.
https://github.com/shellhub-io/shellhub/blob/905dd1afae46b5cae63a6591a80a471d738cc3b2/bin/docker-compose#L58
2) The `bin/utils` doesn't need to be executable.

**Comment by heiytor** [comment]
> 1. `$COMPOSE_ARGS` is no longer defined.
>        https://github.com/shellhub-io/shellhub/blob/905dd1afae46b5cae63a6591a80a471d738cc3b2/bin/docker-compose#L58
> 
>     2. The `bin/utils` doesn't need to be executable.

Resolved.

**Comment by heiytor** [comment]
> 1. `$COMPOSE_ARGS` is no longer defined.
>        https://github.com/shellhub-io/shellhub/blob/905dd1afae46b5cae63a6591a80a471d738cc3b2/bin/docker-compose#L58
> 
>     2. The `bin/utils` doesn't need to be executable.

Resolved.

**Pull request merged**
