### PR TITLE
ui: Add higher contrast, alignment and use size hierarchy in the v-card

### PR DESCRIPTION
**Pull request by Robinsondssantos**
Higher contrast makes components easier to see, alignment of components to create visual pattern and component size hierarchy to show how important something is

### CODE REVIEW

**Comment by otavio** [comment]
@Robinsondssantos, good to see you here. Please post a screenshot of _before_ and _after_, so it is easier to see the proposed changes.

**Review by noreng-jg — COMMENTED** [review]
Hey Robinson, thanks for the contribution. I think it would be a good ideia
change the color of the button for "add-device" and "add-rule" buttons to the following
files as you proposed in initial dashboard page,

```
ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
ui/src/components/device/Device.vue
```

```vue
<v-btn
	...
      class="v-btn--active"
      text
      color="primary"
>
```

**Comment by Robinsondssantos** [comment]
> @Robinsondssantos, good to see you here. Please post a screenshot of _before_ and _after_, so it is easier to see the proposed changes.

Before:
before

After:
after

**Comment by otavio** [comment]
Can you address @noreng-jg comments as well?

**Comment by Robinsondssantos** [comment]
> Can you address @noreng-jg comments as well?

shure

**Comment by Robinsondssantos** [comment]
> Hey Robinson, thanks for the contribution. I think it would be a good ideia
> change the color of the button for "add-device" and "add-rule" buttons to the following
> files as you proposed in initial dashboard page,
> 
> ```
> ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
> ui/src/components/device/Device.vue
> ```
> 
> ```
> <v-btn
> 	...
>       class="v-btn--active"
>       text
>       color="primary"
> >
> ```



> Hey Robinson, thanks for the contribution. I think it would be a good ideia
> change the color of the button for "add-device" and "add-rule" buttons to the following
> files as you proposed in initial dashboard page,
> 
> ```
> ui/src/components/firewall_rules/FirewallRulesFormDialog.vue
> ui/src/components/device/Device.vue
> ```
> 
> ```
> <v-btn
> 	...
>       class="v-btn--active"
>       text
>       color="primary"
> >
> ```

Hey Vagner, good ideia. Should I generate a new pull request?

**Comment by noreng-jg** [comment]
> Hey Vagner, good ideia. Should I generate a new pull request?

It could be in the same pull request, with a new commit, then you could squash your commits into a single one. :)

**Comment by Robinsondssantos** [comment]
> > Hey Vagner, good ideia. Should I generate a new pull request?
> 
> It could be in the same pull request, with a new commit, then you could squash your commits into a single one. :)

@noreng-jg I did as you commented, please take a look

**Review by noreng-jg — CHANGES_REQUESTED** [review]
I have two considerations before accepting your pull request.

1. The buttons in "add-rule" and "add-device" should follow the pattern of dashboard, with normal size, so you'll have to add the properties of `text`, `v-btn--active` in class and remove the `outlined`.

like that:

```vue
      <v-btn
        class="v-btn--active mr-2"
        text
        color="primary"
        ...
      >
```


2. You should also join your commits into a single one.

A suggested commit message for the changes implemented could be:

```
ui: Change style display presentation for components

Higher contrast for v-main component styling was added followed by
display changes conventions in buttons for "add-rule" and  "add-firewall".
```

Do you agree @leonardojoao ?

**Comment by Robinsondssantos** [comment]
> I have two considerations before accepting your pull request.
> 
> 1. The buttons in "add-rule" and "add-device" should follow the pattern of dashboard, with normal size, so you'll have to add the properties of `text`, `v-btn--active` in class and remove the `outlined`.
> 
> like that:
> 
> ```
>       <v-btn
>         class="v-btn--active mr-2"
>         text
>         color="primary"
>         ...
>       >
> ```
> 
> 1. You should also join your commits into a single one.
> 
> A suggested commit message for the changes implemented could be:
> 
> ```
> ui: Change style display presentation for components
> 
> Higher contrast for v-main component styling was added followed by
> display changes conventions in buttons for "add-rule" and  "add-firewall".
> ```
> 
> Do you agree @leonardojoao ?



> I have two considerations before accepting your pull request.
> 
> 1. The buttons in "add-rule" and "add-device" should follow the pattern of dashboard, with normal size, so you'll have to add the properties of `text`, `v-btn--active` in class and remove the `outlined`.
> 
> like that:
> 
> ```
>       <v-btn
>         class="v-btn--active mr-2"
>         text
>         color="primary"
>         ...
>       >
> ```
> 
> 1. You should also join your commits into a single one.
> 
> A suggested commit message for the changes implemented could be:
> 
> ```
> ui: Change style display presentation for components
> 
> Higher contrast for v-main component styling was added followed by
> display changes conventions in buttons for "add-rule" and  "add-firewall".
> ```
> 
> Do you agree @leonardojoao ?



> I have two considerations before accepting your pull request.
> 
> 1. The buttons in "add-rule" and "add-device" should follow the pattern of dashboard, with normal size, so you'll have to add the properties of `text`, `v-btn--active` in class and remove the `outlined`.
> 
> like that:
> 
> ```
>       <v-btn
>         class="v-btn--active mr-2"
>         text
>         color="primary"
>         ...
>       >
> ```
> 
> 1. You should also join your commits into a single one.
> 
> A suggested commit message for the changes implemented could be:
> 
> ```
> ui: Change style display presentation for components
> 
> Higher contrast for v-main component styling was added followed by
> display changes conventions in buttons for "add-rule" and  "add-firewall".
> ```
> 
> Do you agree @leonardojoao ?

Thank you for your considerations, I will do that

**Review by otavio — APPROVED** [review]

**Review by noreng-jg — APPROVED** [review]

**Comment by gustavosbarreto** [comment]
Hey @Robinsondssantos. We really appreciate your contribution.

@all-contributors please add @Robinsondssantos for code

**Comment by Robinsondssantos** [comment]
> Hey @Robinsondssantos. We really appreciate your contribution.
> 
> @all-contributors please add @Robinsondssantos for code

Thank you so much @gustavosbarreto

**Pull request merged**
