### PR TITLE
ui: Fixed command displayed when added devices

### PR DESCRIPTION
**Pull request by brammp**
Did modifications mentioned in issue   #638

Works as intended , unit test passed on my modifications

### CODE REVIEW

**Comment by gustavosbarreto** [comment]
@brammp Thank you!

Can you  please prepend the name of the component to the commit message. E.g.: `ui: commit message` and  squash the two commits into one?

**Comment by brammp** [comment]
Closing and opening a new pull request since i used wrong commitment subjects
Sorry for that

**Comment by leonardojoao** [comment]
Hello @brammp 
Can you please squash the two commits into one?

**Comment by brammp** [comment]
Sure, sorry for that as well :)

**Pull request closed without merging**
